# Configuración de Build de Netlify
[build]
  # Directorio donde se encuentran las funciones serverless
  functions = "netlify/functions"
  
  # Directorio que Netlify debe publicar como tu sitio web principal
  publish = "public"
